[project]
name = "mail_agent"
version = "0.1.0"
description = "mail_agent using crewAI"
authors = [
    { name = "Your Name", email = "you@example.com" },
]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.98.0,<1.0.0",
]

[project.scripts]
mail_agent = "mail_agent.main:run"
run_crew = "mail_agent.main:run"
train = "mail_agent.main:train"
replay = "mail_agent.main:replay"
test = "mail_agent.main:test"

[build-system]
requires = [
    "hatchling",
]
build-backend = "hatchling.build"
